import java.awt.Font;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import java.awt.Color;
import javax.swing.JComboBox;
import javax.swing.DefaultComboBoxModel;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author julio
 */
public class Lvl1 extends javax.swing.JFrame {

    /**
     * Creates new form Lvl1
     */
    public Lvl1() {
    	setTitle("Nivel 1");
    	this.setResizable(false);
    	setBounds(600, 196, 150, 196);
    	getContentPane().setBackground(new Color(150, 196, 222));
    	setBackground(new Color(150, 191, 216));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton2.setBackground(Color.WHITE);
        jButton3 = new javax.swing.JButton();
        jButton3.setBackground(Color.WHITE);
        jButton4 = new javax.swing.JButton();
        jButton4.setBackground(Color.WHITE);
        jButton5 = new javax.swing.JButton();
        jButton5.setBackground(Color.WHITE);
        
        jButton5.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new Font("Gill Sans MT Condensed", Font.BOLD, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 204));
        jLabel1.setText("1. ¿Cual es el circulo morado?");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/circulomorado.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/circulonaranja.jpg"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/circuloverde.jpg"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/circuloamarillo.jpg"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        
        TiempoFYC tiempo = new TiempoFYC();
        JComboBox comboBox = new JComboBox();
        comboBox.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		String mensaje = comboBox.getSelectedItem().toString();
        		if (mensaje.equals("Jugar")) {
        			jButton5.setEnabled(true);
        			jButton2.setEnabled(true);
        			jButton3.setEnabled(true);
        			jButton4.setEnabled(true);
        			tiempo.setVisible(true);
				}

				if (mensaje.equals("Descripcion")) {
					InfoCyF jM = new InfoCyF();
					jM.setVisible(true);
				}

				if (mensaje.equals("Salir")) {
					System.exit(0);
				}
        	}
        });
        comboBox.setFont(new Font("Segoe UI", Font.BOLD, 14));
        comboBox.setModel(new DefaultComboBoxModel(new String[] {"Jugar", "Descripcion", "Salir"}));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(99)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jButton3)
        				.addComponent(jButton5))
        			.addPreferredGap(ComponentPlacement.RELATED, 208, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(jLabel3)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(jButton2)
        					.addPreferredGap(ComponentPlacement.RELATED))
        				.addComponent(jButton4))
        			.addGap(166))
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(comboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(720, Short.MAX_VALUE))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(177)
        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 463, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(191, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(comboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(5)
        			.addComponent(jLabel1)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(jLabel3)
        					.addGap(29))
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jButton2)
        						.addComponent(jButton5))
        					.addPreferredGap(ComponentPlacement.UNRELATED)))
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jButton3)
        				.addComponent(jButton4))
        			.addContainerGap(53, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    this.setVisible(false);
    Incorreto inc = new Incorreto();
    inc.setVisible(true);
    dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    this.setVisible(false);
    Incorreto inc = new Incorreto();
    inc.setVisible(true);
    dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    this.setVisible(false);
    Incorreto inc = new Incorreto();
    this.setVisible(true);
    inc.setVisible(true);
    dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    this.setVisible(false);
    Correcto cor = new Correcto();
    Lvl2 lev2 = new Lvl2();
    lev2.setVisible(true);
    //cor.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
}
