import java.awt.Font;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import java.awt.Color;
import javax.swing.JComboBox;
import javax.swing.DefaultComboBoxModel;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author julio
 */
public class Lvl2 extends javax.swing.JFrame {

	/**
	 * Creates new form Lvl2
	 */
	public Lvl2() {
		setTitle("Nivel 2");
		setBounds(200, 375, 150, 196);
		getContentPane().setBackground(new Color(135, 206, 250));
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jButton1.setBackground(Color.WHITE);
		jButton2 = new javax.swing.JButton();
		jButton2.setBackground(Color.WHITE);
		jButton3 = new javax.swing.JButton();
		jButton3.setBackground(Color.WHITE);

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setFont(new Font("Gill Sans MT Condensed", Font.BOLD, 34)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(204, 0, 204));
		jLabel1.setText("2. Selecciona el triángulo");

		jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/triangu.jpg"))); // NOI18N
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/circulomorado.jpg"))); // NOI18N
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rombo.jpg"))); // NOI18N
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		TiempoFYC tiempo = new TiempoFYC();
		JComboBox comboBox = new JComboBox();
		comboBox.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				String mensaje = comboBox.getSelectedItem().toString();

				if (mensaje.equals("Descripcion")) {
					InfoCyF jM = new InfoCyF();
					jM.setVisible(true);
				}

				if (mensaje.equals("Salir")) {
					System.exit(0);
				}
			}
		});
		comboBox.setFont(new Font("Segoe UI", Font.BOLD, 14));
		comboBox.setModel(new DefaultComboBoxModel(new String[] { "Descripcion", "Salir" }));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.TRAILING).addGroup(layout.createSequentialGroup()
				.addComponent(comboBox, GroupLayout.PREFERRED_SIZE, 123, GroupLayout.PREFERRED_SIZE).addGap(935))
				.addGroup(layout.createSequentialGroup().addGap(120)
						.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 260, GroupLayout.PREFERRED_SIZE).addGap(18)
						.addComponent(jButton2, GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE).addGap(18)
						.addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 270, GroupLayout.PREFERRED_SIZE)
						.addGap(155))
				.addGroup(layout.createSequentialGroup().addContainerGap(384, Short.MAX_VALUE)
						.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 302, GroupLayout.PREFERRED_SIZE)
						.addGap(372)));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(comboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addGap(12).addComponent(jLabel1).addGap(18)
						.addGroup(layout.createParallelGroup(Alignment.LEADING)
								.addComponent(jButton3, GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
								.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
										.addComponent(jButton2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(jButton1, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 234,
												GroupLayout.PREFERRED_SIZE)))
						.addGap(19)));
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		Sonido sound = new Sonido();
		sound.ReproducirSonido("src/chicharra-error-incorrecto-.wav");
	}// GEN-LAST:event_jButton2ActionPerformed

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
		Sonido sound = new Sonido();
		sound.ReproducirSonido("src/chicharra-error-incorrecto-.wav");
	}// GEN-LAST:event_jButton3ActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		this.setVisible(false);
		Correcto cor = new Correcto();
		Lvl3 lev3 = new Lvl3();
		lev3.setVisible(true);

		Sonido sound = new Sonido();
		sound.ReproducirSonido("src/006202921_prev.wav");
		// cor.setVisible(true);
	}// GEN-LAST:event_jButton1ActionPerformed

	/**
	 * @param args the command line arguments
	 */

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JLabel jLabel1;
}
