import java.awt.Font;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import java.awt.Color;
import javax.swing.JComboBox;
import javax.swing.DefaultComboBoxModel;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author julio
 */
public class Lvl4 extends javax.swing.JFrame {

    /**
     * Creates new form Lvl4
     */
    public Lvl4() {
    	setTitle("Nivel 4");
    	setBounds(600, 196, 150, 196);
    	getContentPane().setBackground(Color.WHITE);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton2.setBackground(new Color(176, 224, 230));
        jButton3 = new javax.swing.JButton();
        jButton3.setBackground(new Color(176, 224, 230));
        jButton4 = new javax.swing.JButton();
        jButton4.setBackground(new Color(176, 224, 230));
        jButton5 = new javax.swing.JButton();
        jButton5.setBackground(new Color(176, 224, 230));
        jButton6 = new javax.swing.JButton();
        jButton6.setBackground(new Color(176, 224, 230));
        jButton7 = new javax.swing.JButton();
        jButton7.setBackground(new Color(176, 224, 230));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new Font("Gill Sans MT Condensed", Font.BOLD, 34)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 204));
        jLabel1.setText("4. ¿Qué colores hay en la pelota?");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pelotacolores.png")));

        jButton2.setFont(new Font("Dubai Light", Font.BOLD, 15)); // NOI18N
        jButton2.setText("Azul, Naranja y Rojo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new Font("Dubai Light", Font.BOLD, 15)); // NOI18N
        jButton3.setText("Verde, Blanco y Amarillo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new Font("Dubai Light", Font.BOLD, 15)); // NOI18N
        jButton4.setText("Celeste, Rosado y Azul");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new Font("Dubai Light", Font.BOLD, 15)); // NOI18N
        jButton5.setText("Azul, Amarillo y Rojo");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new Font("Dubai Light", Font.BOLD, 15)); // NOI18N
        jButton6.setText("Verde, Naranja y Rosa");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new Font("Dubai Light", Font.BOLD, 15)); // NOI18N
        jButton7.setText("Negro, Blanco y Gris");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        
        TiempoFYC tiempo = new TiempoFYC();
        comboBox = new JComboBox();
        comboBox.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		String mensaje = comboBox.getSelectedItem().toString();

				if (mensaje.equals("Descripcion")) {
					InfoCyF jM = new InfoCyF();
					jM.setVisible(true);
				}

				if (mensaje.equals("Salir")) {
					System.exit(0);
				}
        	}
        });
        comboBox.setFont(new Font("Segoe UI", Font.BOLD, 14));
        comboBox.setModel(new DefaultComboBoxModel(new String[] {"Descripcion", "Salir"}));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(97)
        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 383, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(108, Short.MAX_VALUE))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(31)
        			.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 288, GroupLayout.PREFERRED_SIZE)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(12)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jButton3, GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
        						.addComponent(jButton2, GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
        						.addComponent(jButton4, GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)))
        				.addGroup(layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jButton6, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
        						.addComponent(jButton5, GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
        						.addComponent(jButton7, GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))))
        			.addGap(62))
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(comboBox, GroupLayout.PREFERRED_SIZE, 123, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(547, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(comboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(5)
        			.addComponent(jLabel1)
        			.addGap(20)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(34)
        					.addComponent(jLabel2))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(26)
        					.addComponent(jButton2)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(jButton3)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(jButton4)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(jButton5)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(jButton6)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(jButton7)))
        			.addGap(111))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    this.setVisible(false);
    Incorreto inc = new Incorreto();
    this.setVisible(true);
    inc.setVisible(true);
    dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    this.setVisible(false);
    Incorreto inc = new Incorreto();
    this.setVisible(true);
    inc.setVisible(true);
    dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    this.setVisible(false);
    Incorreto inc = new Incorreto();
    this.setVisible(true);
    inc.setVisible(true);
    dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    this.setVisible(false);
    Incorreto inc = new Incorreto();
    this.setVisible(true);
    inc.setVisible(true);
    dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
    this.setVisible(false);
    Incorreto inc = new Incorreto();
    this.setVisible(true);
    inc.setVisible(true);
    dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    this.setVisible(false);
    Correcto cor = new Correcto();
    Lvl5 lev5 = new Lvl5();
    lev5.setVisible(true);
    //cor.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private JComboBox comboBox;
    // End of variables declaration//GEN-END:variables
}
